# You can select pixiv or pixiv.moe by following value
# -'//pixiv.moe'
# -'//pixiv.net'
source: '//pixiv.moe'

# If you chose pixiv as image origin, downloading original image required auth or it'll returning 403 error 
pixiv:
  account: 
  password: 

#frequency of chwall.sh/chwall_win.rb and kabe.rb
#minutes
frequency:
  change_wallpapper: 15
  download_new_image: 60
